article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='article'

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.UpdateArticle,name="update"),
    path('delete/<int:id>',views.DeleteArticle,name="delete"),
    path('',views.articles,name="articles"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('articles/',include("article.urls")),
     path('user/',include("user.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='user'

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logUserout,name="logout")
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author=models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar")
    title=models.CharField(max_length=50,verbose_name="Başlık")
    content=RichTextField()
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image=models.FileField(blank=True,null=True,verbose_name="Makale Fotoğraf Ekleyin")
    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = ("title","content","article_image")

user/forms.py
from django import forms

class RegisterForm(forms.Form):
    username=forms.CharField(max_length='50',label='Kullanıcı Adı')
    password=forms.CharField(max_length='12',label='Parola',widget=forms.PasswordInput)
    confirm=forms.CharField(max_length='12',label='Parola Doğrula',widget=forms.PasswordInput)

    def clean(self):
        username=self.cleaned_data.get('username')
        password=self.cleaned_data.get('password')
        confirm=self.cleaned_data.get('confirm')

        if password and confirm and password != confirm:
            raise forms.ValidationError('Parolalar eşleşmiyor')
    
        values= {
            "username": username,
            "password": password


        }

        return values

class LoginUserForm(forms.Form):
    username=forms.CharField(max_length='50',label='Kullanıcı Adı')
    password=forms.CharField(max_length='12',label='Parola',widget=forms.PasswordInput)
    
    values= {
            "username": username,
            "password": password}

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from.models import Article
from django.contrib import messages
# Create your views here.

def articles(request):
    articles=Article.objects.all()

    return render(request,"articles.html",{"articles":articles})





def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")
@login_required(login_url="user:login")
def dashboard(request):
    articles=Article.objects.filter(author=request.user)
    return render(request,"dashboard.html",{"articles":articles})
@login_required(login_url="user:login")
def addarticle(request):

    form=ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Makaleniz Başarıyla Eklenmiştir.")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    #article=Article.objects.filter(id=id).first()
    article=get_object_or_404(Article,id=id)
    return render(request,"detail.html",{"article":article})
@login_required(login_url="user:login")
def UpdateArticle(request,id):
    article=get_object_or_404(Article,id=id)
    form=ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Makaleniz Başarıyla Güncellendi.")
        return redirect("index")

    return render(request,"update.html",{"form":form})
@login_required(login_url="user:login")
def DeleteArticle(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard")

user/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from.forms import RegisterForm,LoginUserForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
# Create your views here.

def register(request):
    

    form=RegisterForm(request.POST or None)
    if form.is_valid():
        username=form.cleaned_data.get('username')
        password=form.cleaned_data.get('password')

        newUser=User(username=username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        return redirect('index')


    context= {

        'form':form
    }

     
    return render(request,"register.html",context)

def loginUser(request):
    form=LoginUserForm(request.POST or None)
    
    context= {

        'form':form
    }
    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")
        
        user=authenticate(username=username,password=password)
        if user is None:
            messages.info(request,"Kullanıcı adı ya da parola hatalı")
            return render(request,"login.html",context)
    
        messages.success(request,"Başarılı Giriş")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)
def logUserout(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")

templates/about.html
{% extends 'layout.html' %}

{% block body %}

<h3>Hakkımızda</h3>


{% endblock body %}

templates/addarticle.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %} 


<div class="row">
  <div class="col-md-6 offset-md-3"><h3>Makale Ekle</h3>
<hr>

<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form.media}}
{{form|crispy}}

<button type='submit' class='btn btn-danger'>Makale Ekle</button>
</form></div>
</div>


{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}

{% block body %}


<div>
{% if articles %}
    {% for article in articles  %}


    <div class="row" style="padding-left:100px">
    <div class="col-md-10 offset-md-2">
        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <a href="/articles/article/{{article.id}}"><h3 class="mt-4">{{article.title}}</h3></a>

            <hr>

            <!-- Preview Image -->
            {% if article.article_image %}
            <a href="/articles/article/{{article.id}}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
            {% endif %}
            <hr>
            <!-- Author -->
            <p class="text-left">
            {{article.created_date}} tarihinde
            <a href="#">{{article.author}}</a> Tarafından yayınlandı.
            </p>

            <!-- Post Content -->
            <p class="lead">
            {{article.content|safe|truncatewords:50}}
            <a href="/articles/article/{{article.id}}" class="btn btn-link">Devamını Oku</a>
            
            </p>

            <hr>
            </div>
        </div>
        </div>
    {% endfor %}    
{% else %}
        <div class="alert alert-danger">
            Makale yok
        </div>
{% endif %}








{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}


<h3>Kontrol Paneli</h3>
<hr>
<p>Hoşgeldin {{request.user.username}}</p>
<hr>

{% if articles %}
    <table class="table">
    <thead class="thead-dark">
        <tr>
        <th scope="col">ID</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles  %}
        <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="{% url "article:detail" article.id %}">{{article.title}}</a></td>
        <td>{{article.author}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="{% url "article:update" article.id %}" class = "btn btn-danger">Güncelle</a></td>
        <td><a href="{% url "article:delete" article.id %} "class = "btn btn-danger">Sil</a></td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% else %}
<div class="alert alert-danger"> Henüz makaleniz yok</div>
{% endif %}
<a class="btn btn-danger" href="{% url "article:addarticle" %}">Makale Ekle</a>

{% endblock body %}

templates/detail.html
{% extends 'layout.html' %}

{% block body %}


<div class="row" style="padding-left:250px">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{article.author}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        {% endif %}
        <hr>

        <!-- Post Content -->
        <p class="lead">
        {{article.content|safe}}
        
        
        </p>

        <hr>
    </div>





{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Ceaser</a>
    <img src="/ceaser.svg" alt="">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Anasayfa <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/articles">Makaleler</a>
        
      </ul>
      
          
        
      
      <form class="form-inline my-2 my-lg-0">
        
        {% if request.user.is_authenticated %}
          <ul class="navbar-nav mr-sm-2">
            <li class="nav-item">
              <a class="nav-link" href="/articles/dashboard">Dashboard</a>
            </li>
            {% if request.user.is_staff %}
          <ul class="navbar-nav mr-sm-2">
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin Paneli</a>
            </li>
          </ul>
          {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="/user/logout">Çıkış Yap</a>
            </li>
          </ul>
          
          <span class="navbar-text" style="color:red">
            Hoşgeldin {{request.user.username}}
          </span>
          
        {% else %}
          <ul class="navbar-nav mr-sm-2">
            <li class="nav-item">
              <a class="nav-link" href="/user/register">Kayıt Ol</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/user/login">Giriş Yap</a>
            </li>
          </ul>

        {% endif %}

      </form>
    </div>
  </nav>

templates/index.html
{% extends 'layout.html' %}

{% block body %}


<div>

<h3>Ceaser</h3>

<img src="./media/augu1.jpg" class="img-fluid rounded">
<b>
<p>{% lorem how_many_paragraphs %}</p>


</div>



{% endblock body %} 

templates/layout.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title>Ertekin Blog</title>
</head>
<body style="background-color:#bd2130">
    
    {% include "includes/navbar.html"  %}

    <div style="margin-top : 100px;" class="jumbotron text-center container">
    {% if messages %}
        
            {% for message in messages %}
            {% if message.tags == "info" %}
                <div class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endif %}
                
            {% endfor %}
        
        {% endif %}
        {% block body %}
        
        
        {% endblock body %}


    </div>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %} 


<div class="row">
  <div class="col-md-6 offset-md-3"><h3>Giriş Yap</h3>
<hr>

<form method="post">
{% csrf_token %}
{{form|crispy}}

<button type='submit' class='btn btn-danger'>Giriş Yap</button>
</form></div>
</div>


{% endblock body %}

templates/register.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block body %} 

<div class="row">
  <div class="col-md-6 offset-md-3"><h3>Kayıt ol</h3>
<hr>

<form method="post">
{% csrf_token %}
{{form|crispy}}

<button type='submit' class='btn btn-danger'>Kayıt Ol</button>
</form></div>
</div>




{% endblock body %}

templates/update.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %} 


<div class="row">
  <div class="col-md-6 offset-md-3"><h3>Makale Güncelle</h3>
<hr>

<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form.media}}
{{form|crispy}}

<button type='submit' class='btn btn-danger'>Makale Güncelle</button>
</form></div>
</div>


{% endblock body %}